### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by sol3uk** [PavN93/Online-quiz#1]
**What did you do well?**
![Well done!](https://media.giphy.com/media/aLdiZJmmx4OVW/giphy.gif)
- Good use of animations, images, style and layout.
- Repository contains quality README with description, screenshot, link to deployed application.
- Application user experience is intuitive and easy to navigate.
- Application user interface style is clean and polished.
- Application resembles the mock-up functionality provided in homework instructions.

**Suggested improvements (Doesn't affect grade)**
- There's a couple of bugs where I can click buttons multiple times. Also sometimes I am able to get multiple screens to appear at once (high screen and start quiz).
- I can save a highscore with no name!

**GRADE:** A+
[BCS](https://bootcampspot.com/gradebook/79274/grade/58220)

You can let us know about any changes by tagging us in a comment below using "@".

**Comment by PavN93** [comment]
@sol3uk Issues with multiple screens and clicking many buttons (and picking the same answer for many questions) is sorted.

**Comment by PavN93** [comment]
@sol3uk User can no longer submit highscores without name. All issues sorted, few other discovered. Will investigate at some point.
